In [1]:
import numpy as np

### Genere un array cuyos valores esten comprendido en el rango -123 a 145

In [4]:
a=np.arange(-123,145)

In [5]:
a

array([-123, -122, -121, -120, -119, -118, -117, -116, -115, -114, -113,
       -112, -111, -110, -109, -108, -107, -106, -105, -104, -103, -102,
       -101, -100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,
        -90,  -89,  -88,  -87,  -86,  -85,  -84,  -83,  -82,  -81,  -80,
        -79,  -78,  -77,  -76,  -75,  -74,  -73,  -72,  -71,  -70,  -69,
        -68,  -67,  -66,  -65,  -64,  -63,  -62,  -61,  -60,  -59,  -58,
        -57,  -56,  -55,  -54,  -53,  -52,  -51,  -50,  -49,  -48,  -47,
        -46,  -45,  -44,  -43,  -42,  -41,  -40,  -39,  -38,  -37,  -36,
        -35,  -34,  -33,  -32,  -31,  -30,  -29,  -28,  -27,  -26,  -25,
        -24,  -23,  -22,  -21,  -20,  -19,  -18,  -17,  -16,  -15,  -14,
        -13,  -12,  -11,  -10,   -9,   -8,   -7,   -6,   -5,   -4,   -3,
         -2,   -1,    0,    1,    2,    3,    4,    5,    6,    7,    8,
          9,   10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
         20,   21,   22,   23,   24,   25,   26,   

### Invertir el array generado en el apartado anterior

In [7]:
np.flip(a)

array([ 144,  143,  142,  141,  140,  139,  138,  137,  136,  135,  134,
        133,  132,  131,  130,  129,  128,  127,  126,  125,  124,  123,
        122,  121,  120,  119,  118,  117,  116,  115,  114,  113,  112,
        111,  110,  109,  108,  107,  106,  105,  104,  103,  102,  101,
        100,   99,   98,   97,   96,   95,   94,   93,   92,   91,   90,
         89,   88,   87,   86,   85,   84,   83,   82,   81,   80,   79,
         78,   77,   76,   75,   74,   73,   72,   71,   70,   69,   68,
         67,   66,   65,   64,   63,   62,   61,   60,   59,   58,   57,
         56,   55,   54,   53,   52,   51,   50,   49,   48,   47,   46,
         45,   44,   43,   42,   41,   40,   39,   38,   37,   36,   35,
         34,   33,   32,   31,   30,   29,   28,   27,   26,   25,   24,
         23,   22,   21,   20,   19,   18,   17,   16,   15,   14,   13,
         12,   11,   10,    9,    8,    7,    6,    5,    4,    3,    2,
          1,    0,   -1,   -2,   -3,   -4,   -5,   

In [6]:
list(reversed(a))

[144,
 143,
 142,
 141,
 140,
 139,
 138,
 137,
 136,
 135,
 134,
 133,
 132,
 131,
 130,
 129,
 128,
 127,
 126,
 125,
 124,
 123,
 122,
 121,
 120,
 119,
 118,
 117,
 116,
 115,
 114,
 113,
 112,
 111,
 110,
 109,
 108,
 107,
 106,
 105,
 104,
 103,
 102,
 101,
 100,
 99,
 98,
 97,
 96,
 95,
 94,
 93,
 92,
 91,
 90,
 89,
 88,
 87,
 86,
 85,
 84,
 83,
 82,
 81,
 80,
 79,
 78,
 77,
 76,
 75,
 74,
 73,
 72,
 71,
 70,
 69,
 68,
 67,
 66,
 65,
 64,
 63,
 62,
 61,
 60,
 59,
 58,
 57,
 56,
 55,
 54,
 53,
 52,
 51,
 50,
 49,
 48,
 47,
 46,
 45,
 44,
 43,
 42,
 41,
 40,
 39,
 38,
 37,
 36,
 35,
 34,
 33,
 32,
 31,
 30,
 29,
 28,
 27,
 26,
 25,
 24,
 23,
 22,
 21,
 20,
 19,
 18,
 17,
 16,
 15,
 14,
 13,
 12,
 11,
 10,
 9,
 8,
 7,
 6,
 5,
 4,
 3,
 2,
 1,
 0,
 -1,
 -2,
 -3,
 -4,
 -5,
 -6,
 -7,
 -8,
 -9,
 -10,
 -11,
 -12,
 -13,
 -14,
 -15,
 -16,
 -17,
 -18,
 -19,
 -20,
 -21,
 -22,
 -23,
 -24,
 -25,
 -26,
 -27,
 -28,
 -29,
 -30,
 -31,
 -32,
 -33,
 -34,
 -35,
 -36,
 -37,
 -38,
 -39,
 -40,
 -41,
 -4

In [9]:
np.invert(a)

array([ 122,  121,  120,  119,  118,  117,  116,  115,  114,  113,  112,
        111,  110,  109,  108,  107,  106,  105,  104,  103,  102,  101,
        100,   99,   98,   97,   96,   95,   94,   93,   92,   91,   90,
         89,   88,   87,   86,   85,   84,   83,   82,   81,   80,   79,
         78,   77,   76,   75,   74,   73,   72,   71,   70,   69,   68,
         67,   66,   65,   64,   63,   62,   61,   60,   59,   58,   57,
         56,   55,   54,   53,   52,   51,   50,   49,   48,   47,   46,
         45,   44,   43,   42,   41,   40,   39,   38,   37,   36,   35,
         34,   33,   32,   31,   30,   29,   28,   27,   26,   25,   24,
         23,   22,   21,   20,   19,   18,   17,   16,   15,   14,   13,
         12,   11,   10,    9,    8,    7,    6,    5,    4,    3,    2,
          1,    0,   -1,   -2,   -3,   -4,   -5,   -6,   -7,   -8,   -9,
        -10,  -11,  -12,  -13,  -14,  -15,  -16,  -17,  -18,  -19,  -20,
        -21,  -22,  -23,  -24,  -25,  -26,  -27,  -

In [11]:
a[::-1]

array([ 144,  143,  142,  141,  140,  139,  138,  137,  136,  135,  134,
        133,  132,  131,  130,  129,  128,  127,  126,  125,  124,  123,
        122,  121,  120,  119,  118,  117,  116,  115,  114,  113,  112,
        111,  110,  109,  108,  107,  106,  105,  104,  103,  102,  101,
        100,   99,   98,   97,   96,   95,   94,   93,   92,   91,   90,
         89,   88,   87,   86,   85,   84,   83,   82,   81,   80,   79,
         78,   77,   76,   75,   74,   73,   72,   71,   70,   69,   68,
         67,   66,   65,   64,   63,   62,   61,   60,   59,   58,   57,
         56,   55,   54,   53,   52,   51,   50,   49,   48,   47,   46,
         45,   44,   43,   42,   41,   40,   39,   38,   37,   36,   35,
         34,   33,   32,   31,   30,   29,   28,   27,   26,   25,   24,
         23,   22,   21,   20,   19,   18,   17,   16,   15,   14,   13,
         12,   11,   10,    9,    8,    7,    6,    5,    4,    3,    2,
          1,    0,   -1,   -2,   -3,   -4,   -5,   

### Generar una matriz 5x4 con valores de impares empezando desde el día de su nacimiento

In [15]:
nacimiento=1992
if nacimiento%2==0:
    print(np.arange(nacimiento+1,nacimiento+41,2).reshape(5,4))
else:
    print(np.arange(nacimiento,nacimiento+41,2).reshape(5,4))

[[1993 1995 1997 1999]
 [2001 2003 2005 2007]
 [2009 2011 2013 2015]
 [2017 2019 2021 2023]
 [2025 2027 2029 2031]]


In [24]:
np.array([x for x in range(nacimiento,nacimiento + 40) if x%2!=0]).reshape(5,4)

array([[1993, 1995, 1997, 1999],
       [2001, 2003, 2005, 2007],
       [2009, 2011, 2013, 2015],
       [2017, 2019, 2021, 2023],
       [2025, 2027, 2029, 2031]])

###  Generar un array de 20 ceros

In [25]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

###  Generar un array de 20 unos

In [26]:
np.ones(20)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

### Generar la matriz identidad de orden 6

In [28]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [29]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

### Generar una matriz con valores al aleatorios con forma 7x6x3 

In [30]:
matriz=np.random.randint(1,30,size=(7,6,3))

In [41]:
np.random.randint(1,30,size=7*6*3).reshape(7,6,3)

array([[[12, 23, 20],
        [14,  4, 20],
        [29, 15, 15],
        [26, 20,  9],
        [27, 24,  3],
        [ 1, 27, 27]],

       [[29, 10, 12],
        [29, 17,  8],
        [ 1, 21, 11],
        [19, 12, 29],
        [ 8, 11, 11],
        [ 3, 29,  2]],

       [[ 4,  6, 15],
        [28,  1,  7],
        [28, 16,  7],
        [15, 18, 21],
        [17, 25, 11],
        [20, 10, 22]],

       [[13, 21,  2],
        [ 4,  1,  7],
        [26, 28, 16],
        [29, 11, 13],
        [ 1, 25,  3],
        [24, 15,  7]],

       [[27, 14, 22],
        [ 2, 29, 26],
        [ 9, 26, 16],
        [14, 20,  3],
        [12, 10,  5],
        [18, 29, 14]],

       [[10, 14, 20],
        [ 5, 28, 23],
        [10,  1, 13],
        [18,  7, 23],
        [25,  9, 26],
        [20, 26, 26]],

       [[ 6, 14,  9],
        [ 6, 21,  8],
        [19,  8,  1],
        [20, 29,  2],
        [10, 15, 22],
        [ 3, 22, 17]]])

In [40]:
np.random.random(size=7*6*3).reshape(7,6,3)

array([[[8.77818684e-01, 7.44868497e-01, 6.76756495e-01],
        [9.51606709e-01, 6.81476532e-01, 7.92598873e-01],
        [1.61434842e-01, 1.78268155e-01, 3.58898212e-02],
        [1.81010954e-01, 9.94623751e-01, 8.06579429e-01],
        [2.73892053e-01, 3.80582982e-01, 7.69741785e-01],
        [9.05165793e-01, 6.89572666e-01, 1.65963060e-01]],

       [[6.64521697e-01, 8.12032928e-01, 5.15201763e-01],
        [8.45390794e-01, 4.44669361e-01, 8.34987617e-01],
        [2.44936152e-01, 4.82893868e-01, 3.64314723e-01],
        [3.89876893e-01, 8.11877389e-02, 2.93843614e-01],
        [6.71357629e-01, 4.45147425e-01, 3.49528529e-01],
        [1.36937510e-01, 7.29337481e-01, 2.62024973e-01]],

       [[5.18278674e-01, 5.28826493e-01, 8.98881232e-01],
        [3.14083104e-01, 5.91405623e-01, 3.47401079e-01],
        [5.70470031e-01, 5.00038552e-01, 6.26546259e-01],
        [8.52916536e-01, 9.86655115e-01, 4.63956856e-01],
        [4.90003517e-02, 9.23752116e-01, 1.50546655e-01],
        [2

In [31]:
matriz

array([[[14, 19, 27],
        [27,  4,  5],
        [ 3, 26, 18],
        [15, 16, 26],
        [26, 29,  2],
        [19, 21, 28]],

       [[14, 24, 24],
        [ 4, 27, 28],
        [16, 20,  8],
        [ 8,  9, 24],
        [15, 16, 16],
        [29, 14,  6]],

       [[29, 12, 25],
        [ 7, 12,  6],
        [27,  4,  4],
        [28, 16, 13],
        [24,  3,  1],
        [ 2, 19, 21]],

       [[28,  2,  6],
        [27, 25,  5],
        [21,  6,  5],
        [16,  9, 21],
        [16,  3, 18],
        [16, 28,  5]],

       [[ 9, 22, 20],
        [ 7,  6, 11],
        [22, 27, 14],
        [ 8,  5,  1],
        [16, 11, 10],
        [24, 16,  1]],

       [[24, 19, 20],
        [ 2,  6,  5],
        [13, 26,  2],
        [ 3,  8,  7],
        [18, 21, 12],
        [19, 12, 14]],

       [[11,  7, 28],
        [20,  4,  2],
        [26, 10, 10],
        [ 3, 10, 22],
        [29, 29, 16],
        [14,  2, 25]]])

### Encontrar los valores minimos y maximos de la anterior matriz

In [32]:
np.min(matriz)

1

In [33]:
np.amin(matriz)

1

In [34]:
np.amax(matriz)

29

In [35]:
np.max(matriz)

29

In [36]:
np.argmax(matriz)

13

In [37]:
np.argmin(matriz)

50

### Encontrar los valores minimos y maximos de la anterior matriz por filas

In [44]:
np.arange(0,7*6*3).reshape(7,6,3)

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17]],

       [[ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35]],

       [[ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44],
        [ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53]],

       [[ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71]],

       [[ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107]],

       [[108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117,

In [47]:
np.max(np.arange(0,7*6*3).reshape(7,6,3),axis=2)

array([[  2,   5,   8,  11,  14,  17],
       [ 20,  23,  26,  29,  32,  35],
       [ 38,  41,  44,  47,  50,  53],
       [ 56,  59,  62,  65,  68,  71],
       [ 74,  77,  80,  83,  86,  89],
       [ 92,  95,  98, 101, 104, 107],
       [110, 113, 116, 119, 122, 125]])

* z $\to$  axis = 0
* y $\to$  axis = 1
* x $\to$  axis = 2

In [48]:
# que elemento ocupa la posicion (x=2,y=1,z=0)
np.arange(0,7*6*3).reshape(7,6,3)[0,1,2]


5

In [49]:
# la z me da igual 
np.arange(0,7*6*3).reshape(7,6,3)[:,1,2]

array([  5,  23,  41,  59,  77,  95, 113])

In [50]:
# la x me da igual 
np.arange(0,7*6*3).reshape(7,6,3)[0,1,:]

array([3, 4, 5])

In [52]:
matriz[0,1,2]

5

In [53]:
matriz[:,:,2]

array([[27,  5, 18, 26,  2, 28],
       [24, 28,  8, 24, 16,  6],
       [25,  6,  4, 13,  1, 21],
       [ 6,  5,  5, 21, 18,  5],
       [20, 11, 14,  1, 10,  1],
       [20,  5,  2,  7, 12, 14],
       [28,  2, 10, 22, 16, 25]])

In [55]:
matriz[6]

array([[11,  7, 28],
       [20,  4,  2],
       [26, 10, 10],
       [ 3, 10, 22],
       [29, 29, 16],
       [14,  2, 25]])

In [56]:
matriz

array([[[14, 19, 27],
        [27,  4,  5],
        [ 3, 26, 18],
        [15, 16, 26],
        [26, 29,  2],
        [19, 21, 28]],

       [[14, 24, 24],
        [ 4, 27, 28],
        [16, 20,  8],
        [ 8,  9, 24],
        [15, 16, 16],
        [29, 14,  6]],

       [[29, 12, 25],
        [ 7, 12,  6],
        [27,  4,  4],
        [28, 16, 13],
        [24,  3,  1],
        [ 2, 19, 21]],

       [[28,  2,  6],
        [27, 25,  5],
        [21,  6,  5],
        [16,  9, 21],
        [16,  3, 18],
        [16, 28,  5]],

       [[ 9, 22, 20],
        [ 7,  6, 11],
        [22, 27, 14],
        [ 8,  5,  1],
        [16, 11, 10],
        [24, 16,  1]],

       [[24, 19, 20],
        [ 2,  6,  5],
        [13, 26,  2],
        [ 3,  8,  7],
        [18, 21, 12],
        [19, 12, 14]],

       [[11,  7, 28],
        [20,  4,  2],
        [26, 10, 10],
        [ 3, 10, 22],
        [29, 29, 16],
        [14,  2, 25]]])

### Encontrar los valores minimos y maximos de la anterior matriz por columnas

### Genere una función en la cual el parámentro de entrada sea un vector aleatorio comprendido entre los números 100 y 1000 y devuelva un vector con los números que sean divisibles por 2,3 y 7

* Lo primero ver que entra un vector
* dentro de la función crear un vector vacio
* rellenar ese vector con números que sean divisbles por 2 y por 3 y por 7 por tanto me valdría que fueran divisibles por 42

In [68]:
a=np.array([1,1,42])
def funcion(vector):
    if len(vector)>99 or len(vector)<1001: 
        b=list()
        for i in vector:
            if i%42==0:
                b.append(i)
        return np.array(b)
    else:
        print("Te has equivocado")


In [65]:
funcion(a)

array([42])

In [67]:
if 99<len(np.arange(1,200))<1001:
    print("OK")
else:
    print("Error") 

OK


In [69]:
funcion(np.arange(1,200))

array([ 42,  84, 126, 168])