In [1]:
## Regresion Lienal Generalizada

$$\hat{y} = \alpha + \beta_1 \times  x_1 +\ldots \beta_n \times x_n + \varepsilon$$
$$ MIN \varepsilon ^2 = MIN \sum (y_i - \hat{y}_i)^2$$
$$ MIN \sum (y_i -\alpha + \beta_1 \times  x_1 +\ldots \beta_n \times x_n )^2$$
$$\hat{\beta}= (X^T X)^{-1} X^Ty$$

In [18]:
import pandas as pd
import os
import numpy as np
df=pd.read_csv("./Datos/Valoracion.csv")

In [3]:
df.head()

Anyo    Estado Civil  Valoracion_A  Valoracion_B  Valoracion_C  \
0  2020          Casado          33.1          25.8          30.8   
1  2021          Casado          40.2          36.8          31.4   
2  2019  Separado/Viudo          32.9          26.5          27.8   
3  2020          Casada          34.4          37.0          32.8   
4  2021          Casada          36.8          31.9          32.1   

   Valoracion_D  Valoracion_E  Valoracion_F  Valoracion_G  
0          30.9          31.9          30.8          25.3  
1          26.8          30.8          37.4          37.4  
2          26.4          26.4          30.8          26.4  
3          44.6          28.6          30.8          37.4  
4          29.6          28.6          34.1          31.9

In [19]:
df=df.drop(columns=["Estado Civil"])

In [5]:
df.head()

Anyo  Valoracion_A  Valoracion_B  Valoracion_C  Valoracion_D  Valoracion_E  \
0  2020          33.1          25.8          30.8          30.9          31.9   
1  2021          40.2          36.8          31.4          26.8          30.8   
2  2019          32.9          26.5          27.8          26.4          26.4   
3  2020          34.4          37.0          32.8          44.6          28.6   
4  2021          36.8          31.9          32.1          29.6          28.6   

   Valoracion_F  Valoracion_G  
0          30.8          25.3  
1          37.4          37.4  
2          30.8          26.4  
3          30.8          37.4  
4          34.1          31.9

In [8]:
Variable_Dependiente="Anyo"
Variable_Independiente=['Valoracion_A', 'Valoracion_B', 'Valoracion_C', 'Valoracion_D',
       'Valoracion_E', 'Valoracion_F', 'Valoracion_G']

$$\hat{\beta}= (X^T X)^{-1} X^Ty$$

In [20]:
df_in=np.array(df[Variable_Independiente].values)
df_de=np.array(df[Variable_Dependiente].values)

In [21]:
df_in.T @ df_in

array([[3.53073835e+08, 3.20803390e+08, 3.16652368e+08, 3.14216069e+08,
        3.04120020e+08, 3.24666257e+08, 3.21298631e+08],
       [3.20803390e+08, 2.97175354e+08, 2.89720466e+08, 2.88315421e+08,
        2.78782720e+08, 2.94159550e+08, 2.97965234e+08],
       [3.16652368e+08, 2.89720466e+08, 2.88591229e+08, 2.83713429e+08,
        2.74755134e+08, 2.90492253e+08, 2.89852400e+08],
       [3.14216069e+08, 2.88315421e+08, 2.83713429e+08, 2.85856302e+08,
        2.73762052e+08, 2.88431232e+08, 2.88822798e+08],
       [3.04120020e+08, 2.78782720e+08, 2.74755134e+08, 2.73762052e+08,
        2.67820008e+08, 2.79177764e+08, 2.79229705e+08],
       [3.24666257e+08, 2.94159550e+08, 2.90492253e+08, 2.88431232e+08,
        2.79177764e+08, 2.98704944e+08, 2.94608407e+08],
       [3.21298631e+08, 2.97965234e+08, 2.89852400e+08, 2.88822798e+08,
        2.79229705e+08, 2.94608407e+08, 2.98824077e+08]])

In [25]:
aes=np.linalg.inv(df_in.T @ df_in)@df_in.T@df_de

### bidimensional
$$y=ax+b$$
### Generalizando
$$y=a_1x_1+a_2x_2+...+a_nx_n + b$$

In [ ]:
b=df_de.mean()-

Tengo que multiplicar cada elemento de la lista **aes** 
por su correspondeinte variable en media

In [29]:
df[Variable_Independiente].mean().values

array([34.13825433, 31.29463533, 30.84239133, 30.69647533, 29.69481533,
       31.338318  , 31.344819  ])

In [30]:
len(aes)

7

In [31]:
a=0
for i,j in zip(aes,df[Variable_Independiente].mean().values):
    a+=i*j

In [33]:
np.dot(aes,df[Variable_Independiente].mean().values)

3278.908623784772

In [32]:
a

3278.908623784772

In [34]:
b=df_de.mean()-a

In [35]:
b

-1258.809883784772

In [36]:
aes

array([-40.62565159,  97.06280232,  -2.94603173,  15.06855183,
        12.53404342,  20.02469191,   8.19361609])

$y=-40.62565159\times Valoracion A + 
    97.06280232 \times Valoracion B +
    \ldots
    8.19361609\times Valoracion G -1258.809883784772$ 