In [1]:
import numpy as np

In [2]:
v=[1,2,3,4]
v1=np.array([1,2,3,4])

In [3]:
v.shape

AttributeError: 'list' object has no attribute 'shape'

In [4]:
v1.shape

(4,)

In [5]:
M=np.array([[1,2],[2,4]])

In [6]:
print(M)

[[1 2]
 [2 4]]


In [7]:
np.shape(M)

(2, 2)

In [8]:
M.shape

(2, 2)

$\begin{pmatrix}
1&2&3\\
4&5&6
\end{pmatrix}
$

In [9]:
M1=np.array([[1,2,3],[4,5,6]])

In [10]:
np.shape(M1)

(2, 3)

In [11]:
print("El número de filas es {0} el número de columnas es {1}".format(np.shape(M1)[0],np.shape(M1)[1]))

El número de filas es 2 el número de columnas es 3


In [12]:
M1[0,1]

2

Práctica 1
* filas van a ser el penultimo número de tu DNI/NIE

* columas van a ser el segundo número de tu DNI/NIE

* rellenaremos esa matriz con ceros

In [16]:
dni="47031962"

In [21]:
np.empty([int(dni[:-2]),int(dni[1])])

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [22]:
np.zeros([int(dni[:-2]),int(dni[1])])

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [23]:
np.ones([int(dni[:-2]),int(dni[1])])

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [24]:
## Matriz Identidad
### I_5
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
# A*I=A=I*A

In [26]:
A=np.array([[0,1,2,3,4],[5,6,7,8,9]])

In [27]:
np.shape(A)

(2, 5)

In [28]:
B=np.array([1,2,3,4])

In [ ]:
### Sumar y restar

In [29]:
A+B

ValueError: operands could not be broadcast together with shapes (2,5) (4,) 

In [30]:
C=np.array([5,6,7,8])

In [31]:
B+C

array([ 6,  8, 10, 12])

In [32]:
C+B

array([ 6,  8, 10, 12])

In [33]:
C+B==B+C

array([ True,  True,  True,  True])

In [34]:
C-B

array([4, 4, 4, 4])

In [35]:
B-C

array([-4, -4, -4, -4])

In [36]:
D=np.array([[5,6,7,8,9],[0,1,2,3,4]])

In [37]:
A+D

array([[ 5,  7,  9, 11, 13],
       [ 5,  7,  9, 11, 13]])

In [38]:
A-D

array([[-5, -5, -5, -5, -5],
       [ 5,  5,  5,  5,  5]])

In [39]:
A*C

ValueError: operands could not be broadcast together with shapes (2,5) (4,) 

In [40]:
B*C

array([ 5, 12, 21, 32])

In [41]:
B

array([1, 2, 3, 4])

In [42]:
C

array([5, 6, 7, 8])

In [43]:
A*D

array([[ 0,  6, 14, 24, 36],
       [ 0,  6, 14, 24, 36]])

In [44]:
A/D

C:\Users\j\AppData\Local\Temp\ipykernel_11064\1827223143.py:1: RuntimeWarning: divide by zero encountered in divide
  A/D


array([[0.        , 0.16666667, 0.28571429, 0.375     , 0.44444444],
       [       inf, 6.        , 3.5       , 2.66666667, 2.25      ]])

$A=\begin{pmatrix}
1 & 2 \\
9 & 4 
\end{pmatrix}$

$B=\begin{pmatrix}
3 & 5 \\
7 & 6 
\end{pmatrix}$

$A_{n\times m}$
$B_{m \times p}$

$\begin{pmatrix}
1 & 2 \\
9 & 4 
\end{pmatrix} \times \begin{pmatrix}
3 & 5 \\
7 & 6 
\end{pmatrix}$

$\begin{pmatrix}
1 & 2 \\
9 & 4 
\end{pmatrix} \times \begin{pmatrix}
3 & 5 \\
7 & 6 
\end{pmatrix} = 
\begin{pmatrix}
1\times 3 + 2 \times 7 & 1 \times 5 + 2\times 6 \\
 9\times 3 + 4 \times 7 & 9 \times 5 + 4\times 6
\end{pmatrix}
$

In [45]:
A @ D

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 5)

In [46]:
A.shape

(2, 5)

In [47]:
D.shape

(2, 5)

In [48]:
D

array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

In [49]:
D.T

array([[5, 0],
       [6, 1],
       [7, 2],
       [8, 3],
       [9, 4]])

In [50]:
A@D.T

array([[ 80,  30],
       [255,  80]])

In [51]:
D.T@A

array([[ 0,  5, 10, 15, 20],
       [ 5, 12, 19, 26, 33],
       [10, 19, 28, 37, 46],
       [15, 26, 37, 48, 59],
       [20, 33, 46, 59, 72]])

In [52]:
A*D

array([[ 0,  6, 14, 24, 36],
       [ 0,  6, 14, 24, 36]])

In [53]:
A/D

C:\Users\j\AppData\Local\Temp\ipykernel_11064\1827223143.py:1: RuntimeWarning: divide by zero encountered in divide
  A/D


array([[0.        , 0.16666667, 0.28571429, 0.375     , 0.44444444],
       [       inf, 6.        , 3.5       , 2.66666667, 2.25      ]])

$A^{-1}$

$y=A \times x$

$y/A=x$

$ A^{-1}\times y = x $


$A \times B = I = B \times A$

In [54]:
np.invert(A)

array([[ -1,  -2,  -3,  -4,  -5],
       [ -6,  -7,  -8,  -9, -10]])

In [55]:
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [56]:
np.linalg.inv(A)

LinAlgError: Last 2 dimensions of the array must be square

In [57]:
np.linalg.inv(A@D.T)

array([[-0.064,  0.024],
       [ 0.204, -0.064]])

In [58]:
np.linalg.inv(A@D.T)@(A@D.T)

array([[ 1.00000000e+00,  1.11022302e-16],
       [-5.55111512e-17,  1.00000000e+00]])

Ejemplo 2

En una granja hay gallinas y cerdos
si cuento las patas hay 120 patas
si cuento las cabezas 50 cabezas

2 G + 4 C = 120

G+C=50

$\begin{pmatrix}
2 G + 4C \\
G+C
\end{pmatrix} = \begin{pmatrix} 120 \\ 50 \end{pmatrix}$

$\begin{pmatrix}
2 & 4  \\
1 & 1
\end{pmatrix} \begin{pmatrix} G \\ C \end{pmatrix} = \begin{pmatrix} 120 \\ 50 \end{pmatrix}$

$ \begin{pmatrix} G \\ C \end{pmatrix} = \begin{pmatrix}
2 & 4  \\
1 & 1
\end{pmatrix}^{-1} \begin{pmatrix} 120 \\ 50 \end{pmatrix}$

In [59]:
A=np.array([[2,4],[1,1]])

In [60]:
np.linalg.inv(A)

array([[-0.5,  2. ],
       [ 0.5, -1. ]])

In [61]:
np.linalg.inv(A)@np.array([120,50])

array([40., 10.])

In [62]:
np.linalg.inv(A)@np.array([120,51])

array([42.,  9.])

In [63]:
B=np.array([[2,4],[1,2]])

In [64]:
np.linalg.inv(B)@np.array([120,50])

LinAlgError: Singular matrix

In [65]:
B

array([[2, 4],
       [1, 2]])

* SCD $\to$ Sistema Compatible Determinado $\to$ el sistema tiene unica solución
* SCI $\to$ Sistema Compatible Indeterminado $\to$ el sistema tiene infinita soluciones
* SI $\to$ Sistema Incompatible  $\to$ No tiene solución

In [66]:
np.linalg.solve(A,np.array([120,50]))

array([40., 10.])

In [67]:
np.linalg.solve(B,np.array([120,50]))

LinAlgError: Singular matrix

In [68]:
A.dtype

dtype('int32')

In [69]:
A

array([[2, 4],
       [1, 1]])

In [70]:
2*A

array([[4, 8],
       [2, 2]])

In [71]:
A/2

array([[1. , 2. ],
       [0.5, 0.5]])

In [72]:
0.5*A

array([[1. , 2. ],
       [0.5, 0.5]])

## Ejercicio 4
Resolver el sistema y que muestre por pantalla las soluciones al sistema

$x-3y+2z-w=6$

$2x-4y+5z+2w=13$

$-x+3y-z+3w=-23$

$3x+2y-z-w=6$

x=?? y=?? z=?? w=??

In [75]:
F=np.array([[1,-3,2,-1],
           [2,-4,5,2],
           [-1,3,-1,3],
           [3,2,-1,-1]])

In [76]:
F

array([[ 1, -3,  2, -1],
       [ 2, -4,  5,  2],
       [-1,  3, -1,  3],
       [ 3,  2, -1, -1]])

In [77]:
np.linalg.solve(F,np.array([6,13,-23,6]))

array([-25.,  55.,  75., -46.])