# Pandas

In [1]:
import pandas as pd

La estrucutura de pandas son:
* Series
* Dataframes
* Indices

## Pandas Series
Es un array unidimensional

In [2]:
pd.Series([1,2,3,15,28])

0     1
1     2
2     3
3    15
4    28
dtype: int64

In [3]:
pd.Series([1,2,3,15,28.0])

0     1.0
1     2.0
2     3.0
3    15.0
4    28.0
dtype: float64

In [4]:
datos=pd.Series([1,2,3,15,28])

In [5]:
datos.values

array([ 1,  2,  3, 15, 28], dtype=int64)

In [6]:
type(datos.values)

numpy.ndarray

In [7]:
datos.index

RangeIndex(start=0, stop=5, step=1)

In [8]:
datos=pd.Series([1,2,3,15.0,'28'])

In [9]:
datos.values

array([1, 2, 3, 15.0, '28'], dtype=object)

In [10]:
datos[4]

'28'

In [11]:
datos[1]

2

In [12]:
datos[1:3]

1    2
2    3
dtype: object

In [13]:
nuevos_datos=pd.Series([10,8,7.5,4],index=['Mates',"Ingles","Lengua","Ed_Fisica"])

In [14]:
nuevos_datos

Mates        10.0
Ingles        8.0
Lengua        7.5
Ed_Fisica     4.0
dtype: float64

In [15]:
nuevos_datos[2]

7.5

In [16]:
nuevos_datos['Mates']

10.0

In [17]:
alumnos={"Cono":10,"Jose":9.5,"Gonzalo":0,"Leticia":9.7}

In [18]:
alumnos

{'Cono': 10, 'Jose': 9.5, 'Gonzalo': 0, 'Leticia': 9.7}

In [19]:
alumnos_series=pd.Series(alumnos)

In [20]:
alumnos_series

Cono       10.0
Jose        9.5
Gonzalo     0.0
Leticia     9.7
dtype: float64

### DataFrame

In [21]:
alumnos_Asistencia=pd.Series({"Cono":97,"Jose":95,"Gonzalo":100,"Leticia":80})

In [22]:
pd.DataFrame({"Notas":alumnos_series,"Asistencia":alumnos_Asistencia})

Notas  Asistencia
Cono      10.0          97
Jose       9.5          95
Gonzalo    0.0         100
Leticia    9.7          80

In [23]:
boot=pd.DataFrame({"Notas":alumnos_series,"Asistencia":alumnos_Asistencia})

In [24]:
boot.index

Index(['Cono', 'Jose', 'Gonzalo', 'Leticia'], dtype='object')

In [25]:
boot.columns

Index(['Notas', 'Asistencia'], dtype='object')

In [26]:
boot["Nueva_Columna"]=boot["Notas"]*0.3+boot["Asistencia"]

In [27]:
boot

Notas  Asistencia  Nueva_Columna
Cono      10.0          97         100.00
Jose       9.5          95          97.85
Gonzalo    0.0         100         100.00
Leticia    9.7          80          82.91

In [28]:
import numpy as np
np.random.rand(3,2)

array([[0.29985737, 0.61411861],
       [0.49113785, 0.27151884],
       [0.82377984, 0.45913221]])

In [29]:
pd.DataFrame(np.random.rand(3,2),columns=["col1","col2"],index=["ind1","ind2","ind3"])

col1      col2
ind1  0.161384  0.301066
ind2  0.837526  0.453189
ind3  0.485937  0.179834

In [31]:
datos=[{'a':i,'b':2*i} for i in range(4)]

In [32]:
datos

[{'a': 0, 'b': 0}, {'a': 1, 'b': 2}, {'a': 2, 'b': 4}, {'a': 3, 'b': 6}]

In [33]:
df=pd.DataFrame(datos)

In [34]:
df

a  b
0  0  0
1  1  2
2  2  4
3  3  6

In [35]:
df.columns=["Usuario","Numero"]

In [36]:
df

Usuario  Numero
0        0       0
1        1       2
2        2       4
3        3       6

In [37]:
A=np.zeros(20,dtype=[("usuario",'i8'),('Numero','f8')])

In [38]:
A

array([(0, 0.), (0, 0.), (0, 0.), (0, 0.), (0, 0.), (0, 0.), (0, 0.),
       (0, 0.), (0, 0.), (0, 0.), (0, 0.), (0, 0.), (0, 0.), (0, 0.),
       (0, 0.), (0, 0.), (0, 0.), (0, 0.), (0, 0.), (0, 0.)],
      dtype=[('usuario', '<i8'), ('Numero', '<f8')])

In [39]:
type(A)

numpy.ndarray

In [40]:
df_A=pd.DataFrame(A)

In [41]:
df_A

usuario  Numero
0         0     0.0
1         0     0.0
2         0     0.0
3         0     0.0
4         0     0.0
5         0     0.0
6         0     0.0
7         0     0.0
8         0     0.0
9         0     0.0
10        0     0.0
11        0     0.0
12        0     0.0
13        0     0.0
14        0     0.0
15        0     0.0
16        0     0.0
17        0     0.0
18        0     0.0
19        0     0.0

In [45]:
df_A.head()

usuario  Numero
0        0     0.0
1        0     0.0
2        0     0.0
3        0     0.0
4        0     0.0

In [46]:
df_A.tail()

usuario  Numero
15        0     0.0
16        0     0.0
17        0     0.0
18        0     0.0
19        0     0.0

In [48]:
df_A.sample(5)

usuario  Numero
17        0     0.0
0         0     0.0
3         0     0.0
11        0     0.0
5         0     0.0

In [49]:
df_A[12]

KeyError: 12

In [50]:
df_A.loc[12]

usuario    0.0
Numero     0.0
Name: 12, dtype: float64

In [51]:
df_A.iloc[12]

usuario    0.0
Numero     0.0
Name: 12, dtype: float64

In [53]:
df_A.iloc[0,5]

IndexError: index 5 is out of bounds for axis 0 with size 2

In [54]:
df_A.loc[[0,5]]

usuario  Numero
0        0     0.0
5        0     0.0

In [55]:
df_A.iloc[[0,5]]

usuario  Numero
0        0     0.0
5        0     0.0

In [56]:
Area=pd.Series({'Madrid':1234,'Barcelona':2345,'Sevilla':3456,'Granada':4567})
pobla=pd.Series({'Madrid':123400,'Barcelona':23450,'Sevilla':34560,'Granada':1234})

In [57]:
df_S=pd.DataFrame({'Area':Area,"Poblacion":pobla})

In [58]:
df_S

Area  Poblacion
Madrid     1234     123400
Barcelona  2345      23450
Sevilla    3456      34560
Granada    4567       1234

In [59]:
df_S["Area"]

Madrid       1234
Barcelona    2345
Sevilla      3456
Granada      4567
Name: Area, dtype: int64

In [60]:
df_S["Poblacion"]

Madrid       123400
Barcelona     23450
Sevilla       34560
Granada        1234
Name: Poblacion, dtype: int64

In [65]:
df_S["Densidad"]=df_S["Poblacion"]/df_S["Area"]

In [66]:
df_S

Area  Poblacion    Densidad
Madrid     1234     123400  100.000000
Barcelona  2345      23450   10.000000
Sevilla    3456      34560   10.000000
Granada    4567       1234    0.270199

In [67]:
df_S.loc["Barcelona"]

Area          2345.0
Poblacion    23450.0
Densidad        10.0
Name: Barcelona, dtype: float64

In [68]:
df_S.iloc[1]

Area          2345.0
Poblacion    23450.0
Densidad        10.0
Name: Barcelona, dtype: float64

In [69]:
df_S.loc["Granada","Densidad"]

0.27019925552879354

In [73]:
df_S.iloc[3]["Densidad"]

0.27019925552879354

In [74]:
df_S.iloc[3,2]

0.27019925552879354

In [79]:
df_S

Area  Poblacion    Densidad
Madrid     1234     123400  100.000000
Barcelona  2345      23450   10.000000
Sevilla    3456      34560   10.000000
Granada    4567       1234    0.270199

In [80]:
df_S[df_S["Densidad"]<10]

Area  Poblacion  Densidad
Granada  4567       1234  0.270199

In [84]:
df_S.loc[df_S["Densidad"]<10,["Area","Poblacion"]]

Area  Poblacion
Granada  4567       1234

In [85]:
df_S.loc["Granada","Poblacion"]=1235

In [86]:
df_S

Area  Poblacion    Densidad
Madrid     1234     123400  100.000000
Barcelona  2345      23450   10.000000
Sevilla    3456      34560   10.000000
Granada    4567       1235    0.270199

In [87]:
df_S.loc["Granada","Densidad"]=df_S.loc["Granada","Poblacion"]/df_S.loc["Granada","Area"]

In [88]:
df_S

Area  Poblacion    Densidad
Madrid     1234     123400  100.000000
Barcelona  2345      23450   10.000000
Sevilla    3456      34560   10.000000
Granada    4567       1235    0.270418

In [89]:
pd.read_csv('./Ficheros_CSV/heart.csv')

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [90]:
corazon=pd.read_csv('./Ficheros_CSV/heart.csv')

In [91]:
corazon.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [93]:
corazon.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [94]:
corazon["oldpeak"].max()

6.2

In [95]:
corazon["oldpeak"].min()

0.0