# Pandas

In [1]:
import pandas as pd

La estrucutura de pandas son:
* Series
* Dataframes
* Indices

## Pandas Series
Es un array unidimensional

In [2]:
pd.Series([1,2,3,15,28])

0     1
1     2
2     3
3    15
4    28
dtype: int64

In [3]:
pd.Series([1,2,3,15,28.0])

0     1.0
1     2.0
2     3.0
3    15.0
4    28.0
dtype: float64

In [4]:
datos=pd.Series([1,2,3,15,28])

In [5]:
datos.values

array([ 1,  2,  3, 15, 28], dtype=int64)

In [6]:
type(datos.values)

numpy.ndarray

In [7]:
datos.index

RangeIndex(start=0, stop=5, step=1)

In [10]:
datos=pd.Series([1,2,3,15.0,'28'])

In [11]:
datos.values

array([1, 2, 3, 15.0, '28'], dtype=object)

In [12]:
datos[4]

'28'

In [13]:
datos[1]

2

In [14]:
datos[1:3]

1    2
2    3
dtype: object

In [15]:
nuevos_datos=pd.Series([10,8,7.5,4],index=['Mates',"Ingles","Lengua","Ed_Fisica"])

In [16]:
nuevos_datos

Mates        10.0
Ingles        8.0
Lengua        7.5
Ed_Fisica     4.0
dtype: float64

In [17]:
nuevos_datos[2]

7.5

In [18]:
nuevos_datos['Mates']

10.0

In [19]:
alumnos={"Cono":10,"Jose":9.5,"Gonzalo":0,"Leticia":9.7}

In [20]:
alumnos

{'Cono': 10, 'Jose': 9.5, 'Gonzalo': 0, 'Leticia': 9.7}

In [21]:
alumnos_series=pd.Series(alumnos)

In [22]:
alumnos_series

Cono       10.0
Jose        9.5
Gonzalo     0.0
Leticia     9.7
dtype: float64

### DataFrame

In [23]:
alumnos_Asistencia=pd.Series({"Cono":97,"Jose":95,"Gonzalo":100,"Leticia":80})

In [26]:
pd.DataFrame({"Notas":alumnos_series,"Asistencia":alumnos_Asistencia})

Notas  Asistencia
Cono      10.0          97
Jose       9.5          95
Gonzalo    0.0         100
Leticia    9.7          80

In [27]:
boot=pd.DataFrame({"Notas":alumnos_series,"Asistencia":alumnos_Asistencia})

In [28]:
boot.index

Index(['Cono', 'Jose', 'Gonzalo', 'Leticia'], dtype='object')

In [29]:
boot.columns

Index(['Notas', 'Asistencia'], dtype='object')

In [32]:
boot["Nueva_Columna"]=boot["Notas"]*0.3+boot["Asistencia"]

In [33]:
boot

Notas  Asistencia  Nueva_Columna
Cono      10.0          97         100.00
Jose       9.5          95          97.85
Gonzalo    0.0         100         100.00
Leticia    9.7          80          82.91

In [34]:
import numpy as np
np.random.rand(3,2)

array([[0.37372001, 0.56268109],
       [0.078186  , 0.37290683],
       [0.88281438, 0.36293375]])

In [35]:
pd.DataFrame(np.random.rand(3,2),columns=["col1","col2"],index=["ind1","ind2","ind3"])

col1      col2
ind1  0.849253  0.617835
ind2  0.499212  0.303944
ind3  0.028976  0.037961